export const ROTATION_REASON = {
  SAME_TASK_CONSECUTIVE_DAY: "SAME_TASK_CONSECUTIVE_DAY",
  EMPLOYEE_ALREADY_ASSIGNED: "EMPLOYEE_ALREADY_ASSIGNED",
  MISSING_REQUIRED_SKILL: "MISSING_REQUIRED_SKILL",
  INACTIVE_EMPLOYEE: "INACTIVE_EMPLOYEE",
  NO_ELIGIBLE_EMPLOYEE: "NO_ELIGIBLE_EMPLOYEE",
} as const
